# -*- coding: utf-8 -*-

"""
    Text2Image
    ~~~

    A library to convert large text strings to image files

    :copyright: (c) 2014 by José M. Franco-Valiente.
    :license: MIT, see LICENSE for more details.
"""

__version__ = '0.1-dev'

DEFAULT_IMAGE_FORMAT = "PNG"
DEFAULT_FONT_FILE = "fonts/maven-pro-regular.ttf"
DEFAULT_FONT_COLOR = "#000"
DEFAULT_BG_COLOR = "#FFF"
DEFAULT_FONT_SIZE = 18
DEFAULT_IMAGE_MARGIN = 10
DEFAULT_CHARS_PER_LINE = 80
DEFAULT_SIGNATURE = "Image generated by Text2Image, by @josemi_fv"

TWITTER_LIMIT = 140

from converter import Text2Image